# File format
# publication:
#   <publication_code1>:
#     <module1>: <command-name1>
#     <module2>: <command-name2>
#     ...
#   <publication_code2>:
#     <module1>: <command-name1>
#     <module2>: <command-name2>
#     ...
#
# modules available:
# - backend
# - backend_core
# - frontend

publication:
  'hello-usa':
    backend: usab
    backend_core: usabc
    frontend: usaf
  'hello-canada':
    backend: canb
    backend_core: canbc
    frontend: canf
